from ../datatypes/basic import Datum, Oid
from ../spi import HeapTuple

type AttrNumber* {.importc.} = cuint

{.push header: "utils/syscache.h" .}

type SysCacheIdentifier* = enum
        AGGFNOID = 0,
        AMNAME,
        AMOID,
        AMOPOPID,
        AMOPSTRATEGY,
        AMPROCNUM,
        ATTNAME,
        ATTNUM,
        AUTHMEMMEMROLE,
        AUTHMEMROLEMEM,
        AUTHNAME,
        AUTHOID,
        CASTSOURCETARGET,
        CLAAMNAMENSP,
        CLAOID,
        COLLNAMEENCNSP,
        COLLOID,
        CONDEFAULT,
        CONNAMENSP,
        CONSTROID,
        CONVOID,
        DATABASEOID,
        DEFACLROLENSPOBJ,
        ENUMOID,
        ENUMTYPOIDNAME,
        EVENTTRIGGERNAME,
        EVENTTRIGGEROID,
        FOREIGNDATAWRAPPERNAME,
        FOREIGNDATAWRAPPEROID,
        FOREIGNSERVERNAME,
        FOREIGNSERVEROID,
        FOREIGNTABLEREL,
        INDEXRELID,
        LANGNAME,
        LANGOID,
        NAMESPACENAME,
        NAMESPACEOID,
        OPERNAMENSP,
        OPEROID,
        OPFAMILYAMNAMENSP,
        OPFAMILYOID,
        PARTRELID,
        PROCNAMEARGSNSP,
        PROCOID,
        PUBLICATIONNAME,
        PUBLICATIONOID,
        PUBLICATIONREL,
        PUBLICATIONRELMAP,
        RANGETYPE,
        RELNAMENSP,
        RELOID,
        REPLORIGIDENT,
        REPLORIGNAME,
        RULERELNAME,
        SEQRELID,
        STATEXTNAMENSP,
        STATEXTOID,
        STATRELATTINH,
        SUBSCRIPTIONNAME,
        SUBSCRIPTIONOID,
        SUBSCRIPTIONRELMAP,
        TABLESPACEOID,
        TRFOID,
        TRFTYPELANG,
        TSCONFIGMAP,
        TSCONFIGNAMENSP,
        TSCONFIGOID,
        TSDICTNAMENSP,
        TSDICTOID,
        TSPARSERNAMENSP,
        TSPARSEROID,
        TSTEMPLATENAMENSP,
        TSTEMPLATEOID,
        TYPENAMENSP,
        TYPEOID,
        USERMAPPINGOID,
        USERMAPPINGUSERSERVER


proc SearchSysCache*(cacheId: int, key1, key2, key3,key4: Datum):HeapTuple {. importc .}
proc SysCacheGetAttr*(cacheId: int, heap_tuple: HeapTuple, lang_number: AttrNumber, is_null: ptr bool):Datum {. importc .}

{.pop.}
