name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        nim-channel: [stable]
    name: ${{ matrix.platform }}-nim-${{ matrix.nim-channel }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-channel }}

    - name: Linux Dev dependencies setup      
      run: |
        sudo apt -y update
        sudo apt -y install build-essential postgresql postgresql-contrib libpq-dev postgresql-server-dev-16 || sudo apt -y install build-essential postgresql postgresql-contrib libpq-dev postgresql-server-dev-all

    - name: Nimble setup
      run: |
        nimble -y refresh
        nimble -y install

    - name: Build & Validate Extensions, Types, and Hooks
      run: |
        pgxtool
        pgxtool init
        pgxtool available-hooks
        pgxtool create-project test
        pgxtool create-hook emit_log
        pgxtool create-type factorial
        pgxtool build-extension test
        pgxtool build-extension emit_log
        pgxtool build-extension factorial

